// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Query struct {
}

type User struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	DisplayName *string `json:"displayName,omitempty"`
	Plan        Plan    `json:"plan"`
}

type Plan string

const (
	PlanFree    Plan = "FREE"
	PlanPremium Plan = "PREMIUM"
)

var AllPlan = []Plan{
	PlanFree,
	PlanPremium,
}

func (e Plan) IsValid() bool {
	switch e {
	case PlanFree, PlanPremium:
		return true
	}
	return false
}

func (e Plan) String() string {
	return string(e)
}

func (e *Plan) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Plan(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Plan", str)
	}
	return nil
}

func (e Plan) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Plan) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Plan) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
